CROISSANTJES = 0.39

STOKBROOD = 2.78

KORTINGSBON = 0.50

CROISSANTJES_TOTAAL =  17 * CROISSANTJES
STOKBROOD_TOTAAL = 2 * STOKBROOD
KORTINGSBON_TOTAAL = 3 * KORTINGSBON

totaal = CROISSANTJES_TOTAAL + STOKBROOD_TOTAAL - KORTINGSBON_TOTAAL

print (totaal)